-- AlterTable
ALTER TABLE `Patient` MODIFY `age` VARCHAR(191) NOT NULL,
    MODIFY `date_of_birth` VARCHAR(191) NOT NULL,
    MODIFY `phone` VARCHAR(191) NOT NULL,
    MODIFY `zip_code` VARCHAR(191) NOT NULL;
